### PR TITLE
Use proper HTML5 input types

### PR DESCRIPTION
**Pull request by srsgores**
I have created tests, but am unable to run them.  Perhaps you can advise on contributing tests.

Please review code, and let me know if these fixes work as intended.

### CODE REVIEW

**Comment by martndemus** [comment]
Thank you for contributing @srsgores :+1:.
You can run the tests like normal on any Ember project, by running `ember test`, if that doesn't work for you let me know.

I have looked at the addition of proper HTML5 input types and it seems that by adding them the custom data entry style we created with the form elements is getting broken. You might wan't to make sure that by adding the types, that the custom data entry we use still works.

**Comment by srsgores** [comment]
I did try ``ember server``, then navigating to ``/tests``, but the testing environment wasn't even loading.

I was thinking that may be a problem.  In that case, I was imagining we could have feature detection, and use native implementations if they are available in the user agent, and skip the ui business if they are available.  Kind of like a polyfill.  Not sure if that's what this project was aiming for, so maybe that can live on a fork.

Thoughts?

**Comment by srsgores** [comment]
I now see that travis tests failed.  What are your thoughts?

**Comment by srsgores** [comment]
Why is this closed?

**Comment by martndemus** [comment]
We can't merge this. If you'd like HTML5 forms i'd suggest you go look at `ember-form-for`.

**Comment by srsgores** [comment]
So you're only supporting HTML4?  Am I correctly understanding this?

**Comment by martndemus** [comment]
We support custom input types.

**Pull request closed without merging**
